using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AM.ApplicationCore.Domain
{
    public enum PlaneType
    {
        Boing,
        Airbus
    }
    public class Plane
    {
        public Plane() { }
        public Plane(int capacity, DateTime manufactureDate, int planeId)
        {
            Capacity = capacity;
            ManufactureDate = manufactureDate;
            PlaneId = planeId;
        }

        /*//basic
private string name;
public string GetName() { return name; }
public void SetName(string name) { this.name = name;}
// light version
public string Name { get; set; }//generated by typing prop and double tab on it 

//Full prop
private int number;

public int Number
{
   get { return number; }
   set { number = value; }
}
//propg secure version
public int Nb { get; private set; }

}*/
        public int Capacity { get; set; }
        public DateTime ManufactureDate { get; set; }

        public int PlaneId { get; set; }
        public planeType PlaneType { get; set; }//proprité de base 

        public ICollection<Flight> Flights { get; set; }// proproete de navigation we can you Ilist 

        public override string? ToString()
        {
            return "Datetime" + ManufactureDate + "PlanceId" + PlaneId;
        }
    }
}
